### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jminor** [bantonj/PyTimeCode#3]
Hi, thanks for making this timecode module. I didn't see any sort of license, just a copyright notice. Are you making this available as open source? If so, which license? I would love to use this for a work project.

Thanks!

**Comment by jminor** [comment]
Hi @bantonj - we are interested in using some of the code from PyTimeCode (and likely one of its forks) in OpenTimelineIO https://github.com/PixarAnimationStudios/OpenTimelineIO but we can't unless you pick an open source license for your project. Sorry to be a bother, but could you include a LICENSE.txt stating the licensing for your project? Thanks.

**Comment by bantonj** [comment]
Sorry for the long delay. Have added a MIT license.

**Comment by jminor** [comment]
Thanks!
